version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    container_name: licensing-service-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: